name: Horoscope Bot

on:
  workflow_dispatch:          # 手動実行
  schedule:
    - cron: '0 21 * * *'      # JST 06:00

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: { node-version: 18 }

      - name: Install deps
        run: npm install node-fetch dotenv deepl-node

      # --- テスト（牡羊座のみ） ---
      - name: Test script
        run: node test_horoscope.js
        env:
          NINJAS_API_KEY:      ${{ secrets.NINJAS_API_KEY }}
          DEEPL_API_KEY:       ${{ secrets.DEEPL_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

      # --- 本番（12星座＋暦） ---
      - name: Publish script
        run: node index.js
        env:
          NINJAS_API_KEY:      ${{ secrets.NINJAS_API_KEY }}
          DEEPL_API_KEY:       ${{ secrets.DEEPL_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
